Feature/edamame api integration (#14)
* test rulset

* test

* merged responses

* Implemented edamame deserialization and mappers

* added edamame api credentials

* Substituted edamame api id and key using githubactions

* Fixed unit tests

* Update deploy.yml

* Update deploy.yml

* Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,12 +54,18 @@ jobs:
         with:
           terraform_version: 1.10.2
           terraform_wrapper: false
-      
-      - name: Replace APP ID in appsettings.json
-        run: sed -i 's|__APP-ID__|${{ secrets.EDAMAME_APP_ID }}|g' $GITHUB_WORKSPACE/src/RecipeAPI/appsettings.json
+          
+      - name: Verify appsettings.json Exists
+        run: |
+          if [ ! -f src/RecipeAPI/appsettings.json ]; then
+            echo "Error: appsettings.json not found!"
+            exit 1
+          fi
 
-      - name: Replace APP KEY in appsettings.json
-        run: sed -i 's|__APP-KEY__|${{ secrets.EDAMAME_APP_KEY }}|g' .$GITHUB_WORKSPACE/src/RecipeAPI/appsettings.json
+      - name: Replace settings in appsettings.json
+        run: |
+          sed -i 's|__APP-ID__|${{ secrets.EDAMAME_APP_ID }}|g' src/RecipeAPI/appsettings.json
+          sed -i 's|__APP-KEY__|${{ secrets.EDAMAME_APP_KEY }}|g' src/RecipeAPI/appsettings.json
 
       - name: Terraform Init
         id: init
